import type { Category, Link, Profile } from "./types";

// 1단계(공개 메인 픽셀 맞추기)용 더미 데이터.
// 2단계에서 Supabase 실 데이터로 교체된다.

export const dummyProfile: Profile = {
  avatar_url: "",
  nickname: "서연",
  bio: "카페 · 뷰티 · 여행 기록을 링크로 모아둡니다",
  banner_enabled: true,
  banner_text: "제휴 링크를 통한 판매 발생시 소정의 수수료를 제공받습니다.",
  default_columns: 2,
  business_contact_url: "mailto:hello@seoyeon.link",
};

export const dummyCategories: Category[] = [
  { id: "cafe", name: "카페", order_index: 0, hidden: false },
  { id: "beauty", name: "뷰티", order_index: 1, hidden: false },
  { id: "travel", name: "여행", order_index: 2, hidden: false },
  { id: "draft", name: "비공개 초안", order_index: 3, hidden: true },
];

export const dummyLinks: Link[] = [
  {
    id: "l1",
    category_id: "cafe",
    thumbnail_url: "",
    thumbnail_label: "coffee bag",
    title: "핸드드립 원두 - 에티오피아 예가체프 200g",
    url: "https://smartstore.naver.com/coffee-roastery/products/1",
    order_index: 0,
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "l2",
    category_id: "cafe",
    thumbnail_url: "",
    thumbnail_label: "dripper",
    title: "도자기 드리퍼 1~2인용",
    url: "https://www.coupang.com/vp/products/2",
    order_index: 1,
    created_at: "2026-08-02T00:00:00Z",
  },
  {
    id: "l3",
    category_id: "cafe",
    thumbnail_url: "",
    thumbnail_label: "canister",
    title: "원두 보관용 밀폐 캐니스터",
    url: "https://www.oliveyoung.co.kr/store/goods/3",
    order_index: 2,
    created_at: "2026-08-03T00:00:00Z",
  },
  {
    id: "l4",
    category_id: "cafe",
    thumbnail_url: "",
    thumbnail_label: "glass",
    title: "내열 유리 커피잔 세트",
    url: "https://www.oliveyoung.co.kr/store/goods/4",
    order_index: 3,
    created_at: "2026-08-04T00:00:00Z",
  },
  {
    id: "l5",
    category_id: "beauty",
    thumbnail_url: "",
    thumbnail_label: "lip balm",
    title: "촉촉 립밤 무색 3g",
    url: "https://www.oliveyoung.co.kr/store/goods/5",
    order_index: 0,
    created_at: "2026-08-05T00:00:00Z",
  },
  {
    id: "l6",
    category_id: "beauty",
    thumbnail_url: "",
    thumbnail_label: "ampoule",
    title: "저자극 진정 앰플 30ml",
    url: "https://www.coupang.com/vp/products/6",
    order_index: 1,
    created_at: "2026-08-06T00:00:00Z",
  },
  {
    id: "l7",
    category_id: "beauty",
    thumbnail_url: "",
    thumbnail_label: "suncream",
    title: "무기자차 선크림 SPF50+",
    url: "https://www.oliveyoung.co.kr/store/goods/7",
    order_index: 2,
    created_at: "2026-08-07T00:00:00Z",
  },
  {
    id: "l8",
    category_id: "beauty",
    thumbnail_url: "",
    thumbnail_label: "cushion",
    title: "글로우 쿠션 21호",
    url: "https://www.oliveyoung.co.kr/store/goods/8",
    order_index: 3,
    created_at: "2026-08-08T00:00:00Z",
  },
  {
    id: "l9",
    category_id: "travel",
    thumbnail_url: "",
    thumbnail_label: "stay photo",
    title: "제주 오션뷰 숙소 예약 링크",
    url: "https://www.yanolja.com/reservation/9",
    order_index: 0,
    created_at: "2026-08-09T00:00:00Z",
  },
  {
    id: "l10",
    category_id: "travel",
    thumbnail_url: "",
    thumbnail_label: "luggage",
    title: "기내용 캐리어 20인치",
    url: "https://www.coupang.com/vp/products/10",
    order_index: 1,
    created_at: "2026-08-10T00:00:00Z",
  },
  {
    id: "l11",
    category_id: "travel",
    thumbnail_url: "",
    thumbnail_label: "pouch",
    title: "여행용 세면 파우치",
    url: "https://www.coupang.com/vp/products/11",
    order_index: 2,
    created_at: "2026-08-11T00:00:00Z",
  },
  {
    id: "l12",
    category_id: "draft",
    thumbnail_url: "",
    thumbnail_label: "shirt",
    title: "비공개 카테고리 테스트 링크",
    url: "https://example.com/12",
    order_index: 0,
    created_at: "2026-08-12T00:00:00Z",
  },
  {
    id: "l13",
    category_id: null,
    thumbnail_url: "",
    thumbnail_label: "unsorted",
    title: "미분류 링크 - 공개 페이지에는 렌더링되지 않음",
    url: "https://example.com/13",
    order_index: 0,
    created_at: "2026-08-13T00:00:00Z",
  },
];
